apiVersion: v2
name: emqx-int-chart
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.26.1"

dependencies:
- name: kube-prometheus-stack
  version: 45.0.0
  repository: https://prometheus-community.github.io/helm-charts
  condition: kube-prometheus-stack.enabled
- name: grafana
  version: 6.50.7
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled
- name: prometheus-pushgateway
  version: 2.1.3
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus-pushgateway.enabled
- name: emqx-ee
  version: 4.4.14
  repository: https://repos.emqx.io/charts
  condition: emqx-ee.enabled
- name: mongodb
  version: 13.6.1
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled
- name: redis
  version: 17.7.5
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: postgresql
  version: 12.2.1
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: kafka
  version: 21.0.1
  repository: https://charts.bitnami.com/bitnami
  condition: kafka.enabled
